package com.shustanov.lorimobile.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shustanov.lorimobile.data.timeentry.TimeEntry;
import com.shustanov.lorimobile.data.user.User;
import com.shustanov.lorimobile.data.project.Project;
import com.shustanov.lorimobile.data.task.Task;

import com.shustanov.lorimobile.data.greendao.TimeEntryDao;
import com.shustanov.lorimobile.data.greendao.UserDao;
import com.shustanov.lorimobile.data.greendao.ProjectDao;
import com.shustanov.lorimobile.data.greendao.TaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timeEntryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig taskDaoConfig;

    private final TimeEntryDao timeEntryDao;
    private final UserDao userDao;
    private final ProjectDao projectDao;
    private final TaskDao taskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timeEntryDaoConfig = daoConfigMap.get(TimeEntryDao.class).clone();
        timeEntryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        timeEntryDao = new TimeEntryDao(timeEntryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);

        registerDao(TimeEntry.class, timeEntryDao);
        registerDao(User.class, userDao);
        registerDao(Project.class, projectDao);
        registerDao(Task.class, taskDao);
    }
    
    public void clear() {
        timeEntryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        projectDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
    }

    public TimeEntryDao getTimeEntryDao() {
        return timeEntryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

}
